apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap
  namespace: simple
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="ko">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>ConfigMap 페이지</title>
    </head>
    <body>
        <h1>config-map에 정의된 html 페이지!</h1>
    </body>
    </html>

