apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  namespace: simple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: test-container
        image: "15.165.59.7:30004/simple/test:83be394"  # Docker 이미지
        ports:
        - containerPort: 8080
