apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  namespace: simple
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      nodeSelector: 
        node: worker
      containers:
      - name: test-container
        image: "15.165.59.7:30004/simple/test:d7b7ce7"  # Docker 이미지
        ports:
        - containerPort: 80
        volumeMounts:
        - name: index-html-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: index-html-volume
        configMap:
          name: index-html-configmap  # 위에서 만든 ConfigMap의 이름
---
apiVersion: v1
kind: Service
metadata:
  name: simple-service
  namespace: simple  # 배포할 네임스페이스
spec:
  selector:
    app: test-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000
  type: NodePort
